version: "3"
services:
  mongo1:
    hostname: mongo1
    container_name: mongo1
    image: mongo:3.6.16
    volumes:
      - ./data/mongo1/db:/data/db
      - ./data/mongo1/configdb:/data/configdb
    networks:
      - mongo-dev-net
    expose:
      - 30001
    ports:
      - 30001:30001
    cap_add:
        - NET_ADMIN
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "30001", "--replSet", "devrs" ]
  mongo2:
    hostname: mongo2
    container_name: mongo2
    image: mongo:3.6.16
    volumes:
      - ./data/mongo2/db:/data/db
      - ./data/mongo2/configdb:/data/configdb
    networks:
      - mongo-dev-net
    expose:
      - 30002
    ports:
      - 30002:30002
    cap_add:
        - NET_ADMIN
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "30002", "--replSet", "devrs" ]
  mongo3:
    hostname: mongo3
    container_name: mongo3
    image: mongo:3.6.16
    volumes:
      - ./data/mongo3/db:/data/db
      - ./data/mongo3/configdb:/data/configdb
    networks:
      - mongo-dev-net
    expose:
      - 30003
    ports:
      - 30003:30003
    cap_add:
      - NET_ADMIN
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "30003", "--replSet", "devrs" ]

networks:
  mongo-dev-net: