version: "3"
services:
  mongo1:
    image: mongo:4.2
    volumes:
      - ./data/mongo1/db:/data/db
      - ./data/mongo1/configdb:/data/configdb
    expose:
      - 30001
    ports:
      - 30001:30001
    restart: "no"
    command: ["/usr/bin/mongod", "--bind_ip_all", "--port", "30001", "--replSet", "miReplicaSet"]

  mongo2:
    image: mongo:4.2
    volumes:
      - ./data/mongo2/db:/data/db
      - ./data/mongo2/configdb:/data/configdb
    expose:
      - 30002
    ports:
      - 30002:30002
    restart: "no"
    command: ["/usr/bin/mongod", "--bind_ip_all", "--port", "30002", "--replSet", "miReplicaSet"]

  mongo3:
    image: mongo:4.2
    volumes:
      - ./data/mongo3/db:/data/db
      - ./data/mongo3/configdb:/data/configdb
    expose:
      - 30003
    ports:
      - 30003:30003
    restart: "no"
    command: ["/usr/bin/mongod", "--bind_ip_all", "--port", "30003", "--replSet", "miReplicaSet"]

  docker-hoster:
    image: dvdarias/docker-hoster
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/hosts:/tmp/hosts
